### PR TITLE
I changed a lot of things about the index and path

### PR DESCRIPTION
**Pull request by gabriela-becerra-jala**
Not working the index calculation, but the select event is working

### CODE REVIEW

**Comment by gabriela-becerra-jala** [comment]
@lisandro-montano 
I added the functionality to listen to events. you can use the same structure.

**Comment by gabriela-becerra-jala** [comment]
@lisandro-montano,
Now the functionallity to obtain the correct information from the file clicked with the QFileSystemmodel is implemented.

Please review

**Comment by lisandro-montano** [comment]
@gabriela-becerra-jala Does this selection works only on click? Because we need it to work with right click and space bar only

**Comment by lisandro-montano** [comment]
@gabriela-becerra-jala Or it is only the functionality to retrieve data from one item

**Pull request merged**
